class_name SantaHat
extends RefCounted
## Santa hats for the Characters_1 pack, with a bouncy tip.
##
##     SantaHat.put_on(character)     # always put one on (if the model has a fit)
##     SantaHat.take_off(character)
##     SantaHat.apply(character)      # follow holiday mode (call this when spawning)
##     SantaHat.mode = SantaHat.Mode.ON
##     SantaHat.update_all(get_tree())  # re-apply to everything passed to apply()
##     SantaHat.set_hidden(character, SantaHat.clashes_with(anim))  # e.g. under an umbrella
##
## `character` is an instance of one of the character .glb scenes. The fit
## (size and position on the head) comes from santa_hat_fits.gd, generated by
## tools/santa_hat.py for every model; models with their own hat or helmet
## are skipped. The tip is driven by a SpringBoneSimulator3D, so it lags and
## bounces as the head moves.

enum Mode { AUTO, ON, OFF }

const HAT_SCENE := preload("SantaHat.glb")
const Fits := preload("santa_hat_fits.gd")
const NODE_NAME := "SantaHat"
const GROUP := "santa_hat_candidates"
## Animations whose props pass through the hat (the umbrella canopy and shaft):
## hide the hat while they play.
const CLASHING_ANIMATIONS := ["Umbrella_"]

## AUTO: hats during the holiday season (see season_start / season_end).
static var mode: Mode = Mode.AUTO
## Season as (month, day); may wrap around the new year.
static var season_start := Vector2i(12, 1)
static var season_end := Vector2i(1, 6)

## Spring settings for the tip (see SpringBoneSimulator3D).
static var tip_stiffness := 1.0
static var tip_drag := 0.2
static var tip_gravity := 0.15


static func in_season(date: Dictionary = {}) -> bool:
	if date.is_empty():
		date = Time.get_date_dict_from_system()
	var d := Vector2i(date.month, date.day)
	var after_start := d.x > season_start.x or (d.x == season_start.x and d.y >= season_start.y)
	var before_end := d.x < season_end.x or (d.x == season_end.x and d.y <= season_end.y)
	if season_start <= season_end:
		return after_start and before_end
	return after_start or before_end


static func is_active() -> bool:
	match mode:
		Mode.ON:
			return true
		Mode.OFF:
			return false
	return in_season()


## Model name ("Character_1_1_1") of a character instance.
static func model_name(character: Node) -> String:
	if character.scene_file_path != "":
		return character.scene_file_path.get_file().get_basename()
	if Fits.FITS.has(String(character.name)):
		return String(character.name)
	for mi in character.find_children("*", "MeshInstance3D", true, false):
		if Fits.FITS.has(String(mi.name)):
			return String(mi.name)
	return String(character.name)


static func can_wear(character: Node) -> bool:
	return Fits.FITS.has(model_name(character))


static func has_hat(character: Node) -> bool:
	return _find_hat(character) != null


## Register the character and give it a hat or not, depending on mode.
static func apply(character: Node3D) -> void:
	if not character.is_in_group(GROUP):
		character.add_to_group(GROUP)
	if is_active():
		put_on(character)
	else:
		take_off(character)


## Re-apply to every character previously passed to apply() (after changing mode).
static func update_all(tree: SceneTree) -> void:
	for c in tree.get_nodes_in_group(GROUP):
		if c is Node3D:
			apply(c)


static func clashes_with(anim: String) -> bool:
	for prefix in CLASHING_ANIMATIONS:
		if anim.begins_with(prefix):
			return true
	return false


## Hide or show the hat without removing it (the tip keeps simulating).
static func set_hidden(character: Node, hidden: bool) -> void:
	var hat := _find_hat(character) as Node3D
	if hat:
		hat.visible = not hidden


static func put_on(character: Node3D) -> Node3D:
	var existing := _find_hat(character)
	if existing:
		return existing
	var fit: Array = Fits.FITS.get(model_name(character), [])
	var skel := _character_skeleton(character)
	if fit.is_empty() or skel == null:
		return null
	var head := skel.find_bone("Head")

	var att := BoneAttachment3D.new()
	att.name = NODE_NAME
	att.bone_name = "Head"
	skel.add_child(att)
	var hat := HAT_SCENE.instantiate() as Node3D
	att.add_child(hat)

	# fit: [scale, x, y, z, tilt, head x, y, z, head radius] in character space at the bind pose
	var s: float = fit[0]
	var placed := Transform3D(Basis(Vector3.RIGHT, deg_to_rad(-float(fit[4]))).scaled(Vector3.ONE * s),
			Vector3(fit[1], fit[2], fit[3]))
	hat.transform = skel.get_bone_global_rest(head).affine_inverse() * placed

	var hat_skel := hat.find_children("*", "Skeleton3D", true, false)[0] as Skeleton3D
	var sim := SpringBoneSimulator3D.new()
	sim.name = "TipSpring"
	hat_skel.add_child(sim)
	sim.setting_count = 1
	sim.set_root_bone_name(0, "Tip_1")
	sim.set_end_bone_name(0, "Tip_3")
	sim.set_extend_end_bone(0, true)
	sim.set_end_bone_direction(0, SpringBoneSimulator3D.BONE_DIRECTION_PLUS_Y)
	sim.set_end_bone_length(0, 0.1)
	sim.set_radius(0, 0.03 * s)
	sim.set_stiffness(0, tip_stiffness)
	sim.set_drag(0, tip_drag)
	sim.set_gravity(0, tip_gravity)
	sim.set_gravity_direction(0, Vector3.DOWN)
	sim.set_enable_all_child_collisions(0, true)

	# keep the tip out of the head
	var col := SpringBoneCollisionSphere3D.new()
	sim.add_child(col)
	var root_bone := hat_skel.find_bone("Hat_Root")
	col.bone_name = "Hat_Root"
	var head_centre := Vector3(fit[5], fit[6], fit[7])
	# (the collision offset and radius ignore the hat's scale, so they are given in metres)
	col.position_offset = (placed * hat_skel.get_bone_global_rest(root_bone)).affine_inverse() * head_centre * s
	col.radius = float(fit[8])
	return hat


static func take_off(character: Node) -> void:
	var hat := _find_hat(character)
	if hat:
		hat.get_parent().remove_child(hat)
		hat.queue_free()


static func _find_hat(character: Node) -> Node:
	var skel := _character_skeleton(character)
	return skel.get_node_or_null(NODE_NAME) if skel else null


static func _character_skeleton(character: Node) -> Skeleton3D:
	for s in character.find_children("*", "Skeleton3D", true, false):
		if s.find_bone("Head") >= 0:
			return s
	return null
